language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t parisk85/udemy-docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true parisk85/udemy-docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udemy-docker-react"
  env: "UdemyDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-670338847205"
  bucket_path: "udemy-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY